# dockerfile-alloy
FROM grafana/alloy:latest AS run
COPY config.alloy /etc/alloy/config.alloy
EXPOSE 12345
# CMD ["--server.http.listen-addr=0.0.0.0:12345"]
# ENTRYPOINT ["/bin/alloy"]
# CMD ["run" "/etc/alloy/config.alloy" "--storage.path=/var/lib/alloy/data"]
