---
services:
  http-api:
    build: http-api/.
    environment:
      - SERVICE_NAME=http-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=alloy:4317
      - INSECURE_MODE=true
    ports:
      - "8080:8080"
  alloy:
    image: grafana/alloy:latest
    command: run /etc/alloy/config.alloy --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy



